name: secp256r1
description: >
  A Flutter plugin that support secp256r1 by Keystore on Android and Secure Enclave on iOS.
version: 0.1.0-dev.8
repository: https://github.com/AstroxNetwork/flutter_secp256r1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  # typed_data: ^1.3.1
  tuple: ^2.0.0
  validators: ^3.0.0
  convert: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: com.astrox.secure_p256_plugin
        pluginClass: SecureP256Plugin
      ios:
        pluginClass: SecureP256Plugin
